/** Main application bootstrapper. */
const BOOTSTRAP_SCRIPTS = [
  'js/components/modal-focus.js','js/task-model.js','js/taxonomy-order.js','js/task-filter.js','js/components/task-taxonomy-menu-order.js',
  'js/components/sidebar-taxonomy-drag-hierarchy.js','js/components/sidebar-taxonomy-drag-touch.js','js/components/sidebar-taxonomy-drag-commit.js','js/components/sidebar-taxonomy-drag.js','js/components/task-drag-hierarchy.js',
  'js/repeat/repeat-engine.js','js/components/schedule-repeat-end.js','js/components/schedule-repeat-validation.js',
  'js/storage/db-schema.js','js/storage/db.js','js/storage/repositories.js','js/storage/mappers.js','js/storage/persistence.js','js/storage/data-service.js','js/storage/data-service-completion.js','js/storage/data-service-repeat-state.js',
  'js/storage/data-service-taxonomy.js','js/storage/data-service-reminders.js','js/storage/data-service-taxonomy-drag.js','js/storage/data-service-hierarchy.js'
];
const BOOTSTRAP_MESSAGES = { MODULE_LOAD: 'A required application module could not be loaded.', INTEGRATION: 'Application modules loaded, but one integration is incomplete.', DATABASE_OPEN: 'TodoListDB could not be opened. Existing data was not cleared.', DATABASE_REPAIR: 'Stored data could not be repaired safely. Existing data was not cleared.', HYDRATION: 'Stored data could not be loaded into the application.', UI_INIT: 'Data loaded, but the interface could not finish starting.' };
function loadScript(src) { return new Promise((resolve, reject) => { if (document.querySelector(`script[data-dynamic-src="${src}"]`)) return resolve(); const script = document.createElement('script'); script.src = src; script.dataset.dynamicSrc = src; script.onload = resolve; script.onerror = () => reject(new Error(`Could not load ${src}`)); document.head.appendChild(script); }); }
function reportBootstrapError(stage, error) { const message = BOOTSTRAP_MESSAGES[stage] || 'The application could not finish starting.'; console.error(`[${stage}] ${message}`, error); if (window.AppPersistence?.reportError) return window.AppPersistence.reportError(message, error); let banner = document.getElementById('bootstrap-error-banner'); if (!banner) { banner = document.createElement('div'); banner.id = 'bootstrap-error-banner'; Object.assign(banner.style, { position: 'fixed', left: '50%', bottom: '18px', transform: 'translateX(-50%)', zIndex: '9999', maxWidth: 'min(560px, calc(100vw - 24px))', padding: '10px 14px', borderRadius: '10px', background: '#171717', color: '#fff', border: '1px solid #444', boxShadow: '0 8px 30px rgba(0,0,0,.35)', fontSize: '13px' }); document.body.appendChild(banner); } banner.textContent = message; }
async function runStage(stage, work) { try { return await work(); } catch (error) { reportBootstrapError(stage, error); throw error; } }
function assertIntegrations() { if (!window.ModalFocusManager) throw new Error('Modal focus manager could not be loaded.'); if (!window.TaskModel) throw new Error('Task model could not be loaded.'); if (!window.TasksComponent || !window.TaskDragHierarchyMethods || !window.TaskTaxonomyMenuOrderMethods || !window.TaskFilter) throw new Error('Task hierarchy/taxonomy/filter integration components could not be loaded.'); if (!window.SidebarComponent || !window.TaxonomyOrder || !window.SidebarTaxonomyDragMethods || !window.SidebarTaxonomyDragHierarchyMethods || !window.SidebarTaxonomyDragTouchMethods || !window.SidebarTaxonomyDragCommitMethods) throw new Error('Sidebar taxonomy hierarchy drag components could not be loaded.'); if (!window.RepeatEngine || !window.ScheduleComponent || !window.ScheduleRepeatEndMethods || !window.ScheduleRepeatValidationMethods) throw new Error('Repeat recurrence components could not be loaded.'); }
function installLateIntegrations() { Object.assign(window.TasksComponent, window.TaskDragHierarchyMethods, window.TaskTaxonomyMenuOrderMethods); Object.assign(window.SidebarComponent, window.SidebarTaxonomyDragMethods, window.SidebarTaxonomyDragHierarchyMethods, window.SidebarTaxonomyDragTouchMethods, window.SidebarTaxonomyDragCommitMethods); Object.assign(window.ScheduleComponent, window.ScheduleRepeatEndMethods, window.ScheduleRepeatValidationMethods); }
document.addEventListener('DOMContentLoaded', async () => {
  window.ThemeManager.init();
  try {
    await runStage('MODULE_LOAD', async () => { for (const src of BOOTSTRAP_SCRIPTS) await loadScript(src); });
    await runStage('INTEGRATION', async () => { assertIntegrations(); installLateIntegrations(); window.ModalFocusManager.init(); });
    await runStage('DATABASE_OPEN', () => window.AppPersistence.initialize());
    await runStage('HYDRATION', () => window.AppPersistence.hydrateState());
    await runStage('DATABASE_REPAIR', () => window.AppDataService.repairRepeatState());
    await runStage('UI_INIT', async () => { window.SidebarComponent.init(); window.SidebarComponent.initTaxonomyDrag(); window.WorkspaceControls.init(); window.TasksComponent.init(); window.ScheduleComponent.init(); window.ScheduleComponent.initRepeatEndUi(); window.SubtaskEditorComponent.init(); window.SettingsComponent.init(); });
  } catch (_) { return; }
  console.log('✅ Apple Minimalist To-Do List Application Initialized with IndexedDB persistence.');
});
